spring.application.name=simulator
# Tell Spring Boot where Kafka is running
spring.kafka.producer.bootstrap-servers=localhost:9092

# Tell Spring Boot to convert our Java objects into JSON format before sending
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer